<div class="center">            
    <div class="headline text-center" id="time">
        <!-- Time auto generated by js -->
    </div><!-- /.headline -->
    
    <!-- User name -->
    <div class="lockscreen-name"><?php echo SessionHelper::_get_session('name', 'admincms_logged_details');?></div>
    
    <!-- START LOCK SCREEN ITEM -->
    <div class="lockscreen-item">
        <!-- lockscreen image -->
        <div class="lockscreen-image">
            <img src="<?php echo base_url( SessionHelper::_get_session('profile_image', 'admincms_logged_details') );?>" alt="user image"/>
        </div>
        <!-- /.lockscreen-image -->

        <!-- lockscreen credentials (contains the form) -->
        <div class="lockscreen-credentials">   

            <div class="input-group">
                <input type="password" class="form-control" placeholder="password" />
                <div class="input-group-btn">
                    <button class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i></button>
                </div>
            </div>
        </div><!-- /.lockscreen credentials -->

    </div><!-- /.lockscreen-item -->

    <div class="lockscreen-link">
        <a href="<?php echo site_url('admincms/sitecontrol/login');?>">Or sign in as a different user</a>
    </div>            
</div>